### ISSUE TITLE
Using this

### ISSUE THREAD

**Issue by Moeinich** [CorvusCloudburst/scavenger#12]
I'm trying to run this, but I can't seem to figure out why it doesn't register the slash commands - do you have a small guide on setting it up? I just want to use it for some small clue hunt games on a small community server :)

**Comment by sten-henriksson** [comment]
Set correct scopes "bot" and "adminstrator" worked for me
then create a .env with 
.env ->
DISCORD_TOKEN=""
DISCORD_CLIENT_ID=""
then run `node .\update-scripts\deploy-commands.js`
to start  ` node index.js `
